#!/usr/bin/env bash
set -euo pipefail

score=0

test -f plugins/live2d-avatar/plugin.json && score=$((score + 1))
test -f plugins/live2d-avatar/index.mjs && score=$((score + 1))
test -f plugins/live2d-avatar/assets/ui/index.html && score=$((score + 1))
test -f plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q '"slot": "main-view"' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'ParamMouthOpenY' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'her-text:ui-state' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'config: Record<string, unknown>' apps/desktop/src/main/plugin-loader.ts && score=$((score + 1))
grep -q 'pluginConfig' apps/desktop/src/renderer/main.ts && score=$((score + 1))
grep -Fq 'configOverrides[manifest.id]' apps/desktop/src/main/plugin-loader.ts && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Mao/Mao.model3.json && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Mao/Mao.moc3 && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Mao/Mao.2048/texture_00.png && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Haru/haru_greeter_t03.model3.json && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Haru/haru_greeter_t03.moc3 && score=$((score + 1))
test -f plugins/live2d-avatar/assets/models/Haru/haru_greeter_t03.2048/texture_00.png && score=$((score + 1))
grep -q '../models/Haru/haru_greeter_t03.model3.json' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'ParamA' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'loadModelSettings' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
! grep -q 'DisplayInfo' plugins/live2d-avatar/assets/models/Haru/haru_greeter_t03.model3.json && score=$((score + 1))
grep -q 'OLD_BUNDLED_MODEL_URLS' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'formatError' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'autoFit' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'getFittedScale' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'measureModelBounds' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'lipSyncAttack' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'mapEmotionToExpression' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q 'maxWidthRatio' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'state.app.screen.width' plugins/live2d-avatar/assets/ui/live2d-avatar.js && score=$((score + 1))
grep -q "type: 'file'" packages/sdk/src/plugins/index.ts && score=$((score + 1))
grep -q 'plugins:selectConfigFile' apps/desktop/src/main/index.ts && score=$((score + 1))
grep -q 'selectPluginConfigFile' apps/desktop/src/renderer/main.ts && score=$((score + 1))
grep -q '"type": "file"' plugins/live2d-avatar/plugin.json && score=$((score + 1))
grep -q 'plugin-file-control' apps/desktop/src/renderer/styles.css && score=$((score + 1))
grep -q 'setApplicationMenu' apps/desktop/src/main/index.ts && score=$((score + 1))
grep -q 'onAppMenuCommand' apps/desktop/src/renderer/main.ts && score=$((score + 1))
grep -q 'grid-row: 1' apps/desktop/src/renderer/styles.css && score=$((score + 1))
! grep -q 'plugin-main-surface-replace .text-display' apps/desktop/src/renderer/styles.css && score=$((score + 1))
grep -q 'plugin-ui-main-surface.replace .plugin-ui-surface-frame' apps/desktop/src/renderer/styles.css && score=$((score + 1))
grep -q 'cursor: move' apps/desktop/src/renderer/styles.css && score=$((score + 1))

echo "$score"
